use_frameworks!

target 'MiniFlake_Example' do
  pod 'MiniFlake', :path => '../'

  target 'MiniFlake_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
